# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build ChestsPlusPlus

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache BuildTools
      id: cache-buildtools
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/BuildTools
        key: buildtools-cache-${{ hashFiles('**/spigot-*.jar') }}
    
    - name: Check BuildTools cached
      run: |
        mkdir -p ~/BuildTools
        ls ~/BuildTools
      shell: bash
      
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'

    - name: Run BuildTools 1.17
      working-directory: BuildTools
      run: |
        cd ~/BuildTools
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/BuildTools/build-1.17.sh"
        # run script
        bash ${GITHUB_WORKSPACE}/BuildTools/build-1.17.sh
      shell: bash
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run BuildTools 1.18+
      working-directory: BuildTools
      run: |
        cd ~/BuildTools
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/BuildTools/build-1.18+.sh"
        # run script
        bash ${GITHUB_WORKSPACE}/BuildTools/build-1.18+.sh
      shell: bash
      
    - name: Check BuildTools cached
      run: |
        mkdir -p ~/BuildTools
        ls ~/BuildTools
      shell: bash
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
#     - name: Check Folders
#       run: |
#         ls -R
#       shell: bash
              
    - name: Pre Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: latest
        repo_token: "${{ secrets.GITHUB_TOKEN }}" 
        prerelease: true
        files: |
          ./Server/plugins/ChestsPlusPlus-*.jar

